services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: supermaneminem
      POSTGRES_USER: admin
      POSTGRES_DB: url_short
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
